// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlgG0bw1yHtEippWDWgMpavheFsZbLlRs',
    appId: '1:760339095903:web:8e55610146290b125316ea',
    messagingSenderId: '760339095903',
    projectId: 'challengr-2bc7a',
    authDomain: 'challengr-2bc7a.firebaseapp.com',
    storageBucket: 'challengr-2bc7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABJyWZF9UdPk00OmAUoK1-Gcj219vFxIo',
    appId: '1:760339095903:android:cefcaf1275e780545316ea',
    messagingSenderId: '760339095903',
    projectId: 'challengr-2bc7a',
    storageBucket: 'challengr-2bc7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mCsK684-8iOrP9HgdEIHcFx-oo8ZwfY',
    appId: '1:760339095903:ios:5cc74eceb98e70e15316ea',
    messagingSenderId: '760339095903',
    projectId: 'challengr-2bc7a',
    storageBucket: 'challengr-2bc7a.firebasestorage.app',
    iosBundleId: 'com.example.challengr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9mCsK684-8iOrP9HgdEIHcFx-oo8ZwfY',
    appId: '1:760339095903:ios:5cc74eceb98e70e15316ea',
    messagingSenderId: '760339095903',
    projectId: 'challengr-2bc7a',
    storageBucket: 'challengr-2bc7a.firebasestorage.app',
    iosBundleId: 'com.example.challengr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlgG0bw1yHtEippWDWgMpavheFsZbLlRs',
    appId: '1:760339095903:web:b73b28158dd07a455316ea',
    messagingSenderId: '760339095903',
    projectId: 'challengr-2bc7a',
    authDomain: 'challengr-2bc7a.firebaseapp.com',
    storageBucket: 'challengr-2bc7a.firebasestorage.app',
  );
}
